const produceList = [
    {
      "": "Jan",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "At its best",
      "Cod": "Coming in",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "At its best",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple sprouting broccoli": "Coming in",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "": "Feb",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "At its best",
      "Cod": "At its best",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "",
      "Peas": "",
      "Pepper": "Coming in",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple sprouting broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "": "Mar",
      "Apple": "",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "",
      "Cod": "At its best",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "At its best",
      "Kale": "",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "",
      "Peas": "",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "Coming in",
      "Pumpkin": "",
      "Purple sprouting broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "Coming in",
      "Spinach": "Coming in",
      "Spring greens": "Coming in",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "Coming in",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "": "Apr",
      "Apple": "",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "At its best",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "Coming in",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "",
      "Nectarine": "",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "Coming in",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple sprouting broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "Coming in",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "": "May",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "Coming in",
      "Aubergine": "Coming in",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "Coming in",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "Coming in",
      "Cauliflower": "",
      "Cavolo nero": "",
      "Celeriac": "",
      "Celery": "",
      "Cherry": "",
      "Chervil": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "Coming in",
      "Goose": "",
      "Gooseberry": "Coming in",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Pak choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple sprouting broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "Coming in",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "Coming in",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "": "Jun",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "At its best",
      "Aubergine": "At its best",
      "Banana": "At its best",
      "Basil": "Coming in",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "At its best",
      "Bramley apple": "",
      "Broad bean": "Coming in",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Cavolo nero": "Coming in",
      "Celeriac": "",
      "Celery": "",
      "Cherry": "Coming in",
      "Chervil": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "At its best",
      "Courgette flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "At its best",
      "Fig": "",
      "Garlic": "Coming in",
      "Globe artichoke": "At its best",
      "Goose": "",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Mangetout": "At its best",
      "Marrow": "",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Pak choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple sprouting broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "Coming in",
      "Redcurrant": "Coming in",
      "Rhubarb": "At its best",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "Coming in",
      "Whiting": "At its best"
    },
    {
      "": "Jul",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "At its best",
      "Aubergine": "At its best",
      "Banana": "At its best",
      "Basil": "At its best",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "Coming in",
      "Blackcurrants": "At its best",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "Coming in",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Cavolo nero": "At its best",
      "Celeriac": "",
      "Celery": "Coming in",
      "Cherry": "At its best",
      "Chervil": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "At its best",
      "Courgette flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "At its best",
      "Fig": "Coming in",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "Coming in",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Mangetout": "At its best",
      "Marrow": "Coming in",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Pak choi": "At its best",
      "Parsnip": "",
      "Peach": "Coming in",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple sprouting broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "At its best",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "At its best",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "At its best",
      "Whiting": "At its best"
    },
    {
      "": "Aug",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "",
      "Aubergine": "At its best",
      "Banana": "At its best",
      "Basil": "At its best",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "At its best",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Cavolo nero": "At its best",
      "Celeriac": "",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "At its best",
      "Courgette flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "At its best",
      "Cranberry": "",
      "Damson": "Coming in",
      "Date": "",
      "Duck": "",
      "Elderberries": "At its best",
      "Fennel bulb": "At its best",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "Coming in",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "Coming in",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "At its best",
      "Mackerel": "At its best",
      "Mangetout": "At its best",
      "Marrow": "At its best",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "Coming in",
      "Pak choi": "At its best",
      "Parsnip": "",
      "Peach": "At its best",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "Coming in",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple sprouting broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "At its best",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "Coming in",
      "Swiss chard": "At its best",
      "Tayberry": "At its best",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "At its best",
      "Whiting": "At its best"
    },
    {
      "": "Sep",
      "Apple": "At its best",
      "Apricot": "At its best",
      "Asparagus": "",
      "Aubergine": "At its best",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "At its best",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Cavolo nero": "At its best",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "At its best",
      "Chestnut": "Coming in",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "At its best",
      "Courgette flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Damson": "At its best",
      "Date": "",
      "Duck": "",
      "Elderberries": "At its best",
      "Fennel bulb": "At its best",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "Coming in",
      "Kipper": "At its best",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "At its best",
      "Mackerel": "At its best",
      "Mangetout": "",
      "Marrow": "At its best",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "At its best",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "At its best",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "Coming in",
      "Purple sprouting broccoli": "",
      "Quince": "Coming in",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "Coming in",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "At its best",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "": "Oct",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "At its best",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "At its best",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "",
      "Cavolo nero": "At its best",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Damson": "",
      "Date": "Coming in",
      "Duck": "At its best",
      "Elderberries": "At its best",
      "Fennel bulb": "",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "",
      "Jerusalem artichoke": "Coming in",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "At its best",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple sprouting broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "Coming in",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "Coming in",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "": "Nov",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "Coming in",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "At its best",
      "Cod": "",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Damson": "",
      "Date": "At its best",
      "Duck": "At its best",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple sprouting broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "": "Dec",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Aubergine": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "Coming in",
      "Cavolo nero": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Chervil": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "At its best",
      "Cod": "",
      "Courgette": "",
      "Courgette flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Damson": "",
      "Date": "At its best",
      "Duck": "At its best",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "At its best",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "",
      "Mangetout": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Pak choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple sprouting broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "At its best",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    }
  ]


function watchForm(){
    $('form').submit(event => {
        event.preventDefault();
        const selectedMonth = $('#userMonth').val();
        console.log(selectedMonth);
    });
}

$(watchForm);