const produceList = [
    {
      "Month": "January",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "At its best",
      "Cod": "Coming in",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "At its best",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple broccoli": "Coming in",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "Month": "February",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "At its best",
      "Cod": "At its best",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "",
      "Peas": "",
      "Pepper": "Coming in",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "Month": "March",
      "Apple": "",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "At its best",
      "Clementine": "",
      "Cod": "At its best",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "At its best",
      "Kale": "",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "At its best",
      "Lettuce": "",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "At its best",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "",
      "Peas": "",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "Coming in",
      "Pumpkin": "",
      "Purple broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "Coming in",
      "Spinach": "Coming in",
      "Spring greens": "Coming in",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "Coming in",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "Month": "April",
      "Apple": "",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "At its best",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "At its best",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "Coming in",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "",
      "Nectarine": "",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "Coming in",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple broccoli": "At its best",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "Coming in",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "Month": "May",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "Coming in",
      "Eggplant": "Coming in",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "Coming in",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "Coming in",
      "Cauliflower": "",
      "Italian kale": "",
      "Celeriac": "",
      "Celery": "",
      "Cherry": "",
      "Parsley": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "Coming in",
      "Goose": "",
      "Gooseberry": "Coming in",
      "Grapefruit": "At its best",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Bok choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "At its best",
      "Runner bean": "",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "Coming in",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "Coming in",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": ""
    },
    {
      "Month": "June",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "At its best",
      "Eggplant": "At its best",
      "Banana": "At its best",
      "Basil": "Coming in",
      "Beef": "At its best",
      "Beetroot": "",
      "Blackberry": "",
      "Blackcurrants": "At its best",
      "Bramley apple": "",
      "Broad bean": "Coming in",
      "Broccoli": "",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Italian kale": "Coming in",
      "Celeriac": "",
      "Celery": "",
      "Cherry": "Coming in",
      "Parsley": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "At its best",
      "Zucchini flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "At its best",
      "Fig": "",
      "Garlic": "Coming in",
      "Globe artichoke": "At its best",
      "Goose": "",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Snow pea": "At its best",
      "Marrow": "",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Bok choi": "At its best",
      "Parsnip": "",
      "Peach": "",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "Coming in",
      "Redcurrant": "Coming in",
      "Rhubarb": "At its best",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "At its best",
      "Spring lamb": "At its best",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "Coming in",
      "Whiting": "At its best"
    },
    {
      "Month": "July",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "At its best",
      "Eggplant": "At its best",
      "Banana": "At its best",
      "Basil": "At its best",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "Coming in",
      "Blackcurrants": "At its best",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "Coming in",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Italian kale": "At its best",
      "Celeriac": "",
      "Celery": "Coming in",
      "Cherry": "At its best",
      "Parsley": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "At its best",
      "Zucchini flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "",
      "Date": "",
      "Duck": "",
      "Elderberries": "",
      "Fennel bulb": "At its best",
      "Fig": "Coming in",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "",
      "Guinea fowl": "",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "Coming in",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Snow pea": "At its best",
      "Marrow": "Coming in",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "At its best",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "",
      "Bok choi": "At its best",
      "Parsnip": "",
      "Peach": "Coming in",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "At its best",
      "Pumpkin": "",
      "Purple broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "At its best",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "At its best",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "At its best",
      "Whiting": "At its best"
    },
    {
      "Month": "August",
      "Apple": "",
      "Apricot": "At its best",
      "Asparagus": "",
      "Eggplant": "At its best",
      "Banana": "At its best",
      "Basil": "At its best",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "At its best",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Italian kale": "At its best",
      "Celeriac": "",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "At its best",
      "Chestnut": "",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "At its best",
      "Zucchini flower": "At its best",
      "Crab": "At its best",
      "Crab apple": "At its best",
      "Cranberry": "",
      "Plum": "Coming in",
      "Date": "",
      "Duck": "",
      "Elderberries": "At its best",
      "Fennel bulb": "At its best",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "Coming in",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "Coming in",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "",
      "Kipper": "At its best",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "At its best",
      "Mackerel": "At its best",
      "Snow pea": "At its best",
      "Marrow": "At its best",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "Coming in",
      "Bok choi": "At its best",
      "Parsnip": "",
      "Peach": "At its best",
      "Pear": "",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "Coming in",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "",
      "Purple broccoli": "",
      "Quince": "",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "",
      "Samphire": "At its best",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "Coming in",
      "Swiss chard": "At its best",
      "Tayberry": "At its best",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "At its best",
      "Whiting": "At its best"
    },
    {
      "Month": "September",
      "Apple": "At its best",
      "Apricot": "At its best",
      "Asparagus": "",
      "Eggplant": "At its best",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "At its best",
      "Broccoli": "At its best",
      "Brussels sprouts": "",
      "Cabbage": "At its best",
      "Carrot": "At its best",
      "Cauliflower": "",
      "Italian kale": "At its best",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "At its best",
      "Chestnut": "Coming in",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "At its best",
      "Zucchini flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "",
      "Plum": "At its best",
      "Date": "",
      "Duck": "",
      "Elderberries": "At its best",
      "Fennel bulb": "At its best",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "At its best",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "At its best",
      "Jerusalem artichoke": "",
      "Kale": "Coming in",
      "Kipper": "At its best",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "At its best",
      "Mackerel": "At its best",
      "Snow pea": "",
      "Marrow": "At its best",
      "Mint": "At its best",
      "Mussels": "",
      "Nectarine": "At its best",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "At its best",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "At its best",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "Coming in",
      "Purple broccoli": "",
      "Quince": "Coming in",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "At its best",
      "Redcurrant": "At its best",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "At its best",
      "Salsify": "Coming in",
      "Samphire": "",
      "Sorrel": "At its best",
      "Spinach": "At its best",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "At its best",
      "Swede": "",
      "Sweet potato": "",
      "Sweetcorn": "At its best",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "At its best",
      "Turkey": "",
      "Turnip": "",
      "Venison": "",
      "Watercress": "At its best",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "Month": "October",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "At its best",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "At its best",
      "Blackcurrants": "",
      "Bramley apple": "",
      "Broad bean": "",
      "Broccoli": "At its best",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "",
      "Italian kale": "At its best",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "",
      "Cod": "",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Plum": "",
      "Date": "Coming in",
      "Duck": "At its best",
      "Elderberries": "At its best",
      "Fennel bulb": "",
      "Fig": "At its best",
      "Garlic": "At its best",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "",
      "Jerusalem artichoke": "Coming in",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "At its best",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "At its best",
      "Plum": "At its best",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "At its best",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "Coming in",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "At its best",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "Coming in",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "Month": "November",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "Coming in",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "At its best",
      "Cod": "",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "At its best",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Plum": "",
      "Date": "At its best",
      "Duck": "At its best",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "At its best",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "",
      "Grouse": "At its best",
      "Guinea fowl": "At its best",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "At its best",
      "Lamb": "At its best",
      "Lamb's lettuce": "At its best",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "At its best",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "At its best",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "At its best",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    },
    {
      "Month": "December",
      "Apple": "At its best",
      "Apricot": "",
      "Asparagus": "",
      "Eggplant": "",
      "Banana": "At its best",
      "Basil": "",
      "Beef": "At its best",
      "Beetroot": "At its best",
      "Blackberry": "",
      "Blackcurrants": "",
      "Bramley apple": "At its best",
      "Broad bean": "",
      "Broccoli": "",
      "Brussels sprouts": "At its best",
      "Cabbage": "At its best",
      "Carrot": "",
      "Cauliflower": "Coming in",
      "Italian kale": "",
      "Celeriac": "At its best",
      "Celery": "At its best",
      "Cherry": "",
      "Parsley": "",
      "Chestnut": "At its best",
      "Chicken": "At its best",
      "Chicory": "",
      "Clementine": "At its best",
      "Cod": "",
      "Zucchini": "",
      "Zucchini flower": "",
      "Crab": "",
      "Crab apple": "",
      "Cranberry": "At its best",
      "Plum": "",
      "Date": "At its best",
      "Duck": "At its best",
      "Elderberries": "",
      "Fennel bulb": "",
      "Fig": "",
      "Garlic": "",
      "Globe artichoke": "",
      "Goose": "At its best",
      "Gooseberry": "",
      "Grapefruit": "At its best",
      "Grouse": "At its best",
      "Guinea fowl": "",
      "Halibut": "",
      "Jerusalem artichoke": "At its best",
      "Kale": "At its best",
      "Kipper": "",
      "Kohlrabi": "",
      "Lamb": "At its best",
      "Lamb's lettuce": "",
      "Leek": "At its best",
      "Lemon": "",
      "Lettuce": "At its best",
      "Loganberry": "",
      "Mackerel": "",
      "Snow pea": "",
      "Marrow": "",
      "Mint": "",
      "Mussels": "At its best",
      "Nectarine": "",
      "New potatoes": "",
      "Onion": "At its best",
      "Orange": "",
      "Oyster": "At its best",
      "Bok choi": "At its best",
      "Parsnip": "At its best",
      "Peach": "",
      "Pear": "At its best",
      "Peas": "",
      "Pepper": "",
      "Plum": "",
      "Pomegranate": "At its best",
      "Pork": "At its best",
      "Potato": "",
      "Pumpkin": "At its best",
      "Purple broccoli": "",
      "Quince": "At its best",
      "Radicchio": "At its best",
      "Radish": "",
      "Raspberry": "",
      "Redcurrant": "",
      "Rhubarb": "",
      "Runner bean": "",
      "Salmon": "",
      "Salsify": "At its best",
      "Samphire": "",
      "Sorrel": "",
      "Spinach": "",
      "Spring greens": "",
      "Spring lamb": "",
      "Spring onion": "At its best",
      "Strawberry": "",
      "Swede": "At its best",
      "Sweet potato": "At its best",
      "Sweetcorn": "",
      "Swiss chard": "",
      "Tayberry": "",
      "Tomato": "",
      "Tuna": "",
      "Turkey": "At its best",
      "Turnip": "At its best",
      "Venison": "At its best",
      "Watercress": "",
      "Watermelon": "",
      "Whiting": "At its best"
    }
  ]

let userQuery = '';  

function resetPage(){
    $('#restartApp').click(function(event){
        $('.seasonalRecipes').empty();
        $('.seasonalProduce').empty();
        $('.recipePage').addClass('hidden');
        $('.landingPage').removeClass('hidden');
        userQuery = '';
    });
}

function displayRecipes(responseJson){
    $('.producePage').addClass('hidden');
    $('.recipePage').removeClass('hidden');
    if (responseJson.count == 0) {
        console.log('count 0')
        $('.seasonalRecipes').append(`<p>I'm sorry!<br>There are no recipes containing those ingredients.</p>`);
    } else {
        $('.recipeTitle').removeClass('hidden');
        for (let i=0; i < responseJson.hits.length; i++){
            $('.seasonalRecipes').append(`
            <li class="recipeCard"><h3><a href="${responseJson.hits[i].recipe.shareAs}">
            ${responseJson.hits[i].recipe.label}</a></h3>
            <img src="${responseJson.hits[i].recipe.image}">
            </li>
            `)}
    };
    resetPage();
}

function fetchRecipes(){
    let searchUrl = `https://api.edamam.com/search?q=${userQuery}&app_id=f8a0d09e&app_key=e4b27fdabecbbf429ab8c33ad157001d`;
    console.log(searchUrl);
    fetch(searchUrl)
    .then(response => {
      if (response.ok) {
        return response.json();
      }
      throw new Error(response.statusText);
    })
    .then(responseJson => displayRecipes(responseJson))
    .catch(err => {
      console.log(err.message);
    });
}

function produceListener(){
    $('#produceSection').on('click', 'li', event => {
        $(event.target).addClass('clicked')
        const clickedItem = $(event.target).text();
        if (userQuery != ''){   
            userQuery += '+' + encodeURIComponent(clickedItem);
        } else {
            userQuery = encodeURIComponent(clickedItem);
        }
        console.log(userQuery);
    });
    $('#recipeSubmit').click(event => {
        event.preventDefault();
        fetchRecipes(userQuery);
    });
}

function displayProduce(produceList, month){
    $('.landingPage').addClass('hidden');
    $('.landingLogo').css('height', '50px');
    $('.producePage').removeClass('hidden');
    $('#produceTitle').html(`Here's what's in season during ${month}:`);
    produceList.forEach(appendProduceArray);
    produceListener();
}

function appendProduceArray(item){
    $('.seasonalProduce').append(`
            <li class='produceItem' id='produce'>${item}</li>
        `);
}

function findInSeasonProduce(userInput){
    const monthObj = [];
    const monthIndex = produceList.findIndex(x => x.Month == userInput);
    console.log(monthIndex);
    for (let item in produceList[monthIndex]){
        if (produceList[monthIndex][item] != "" && item != "Month"){
            monthObj.push(item);
        }
    }
    displayProduce(monthObj, userInput);
}

function watchForm(){
    $('form').submit(event => {
        event.preventDefault();
        const selectedMonth = $('#userMonth').val();
        console.log(selectedMonth);
        findInSeasonProduce(selectedMonth);
    });
}

$(watchForm);